name: Validate Go Mod Files

on:
  pull_request:

jobs:
  go-mod-validation:
    name: Validate go.mod dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: Validate go.mod
        uses: smartcontractkit/.github/apps/go-mod-validator@97f9fe6cfe1836266a7a7c094762d0b4a41347da #v0.3.0
